import { createReadStream, existsSync } from 'node:fs';
import { mkdir, readFile, stat, unlink, writeFile } from 'node:fs/promises';
import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { createServer } from 'node:http';
import { extname, join, normalize, resolve } from 'node:path';
import pg from 'pg';

const port = Number(process.env.PORT || 3100);
const publicDir = resolve(process.env.PUBLIC_DIR || join(process.cwd(), 'public'));
const mediaDir = resolve(process.env.MEDIA_DIR || join(process.cwd(), 'media'));
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adminEmail = (process.env.STUDIO_ADMIN_EMAIL || 'abdulrahmanalmushajari@gmail.com').toLowerCase();
const secret = process.env.STUDIO_SESSION_SECRET;
if (!process.env.DATABASE_URL || !secret) throw new Error('DATABASE_URL and STUDIO_SESSION_SECRET are required.');
const allowedOrigins = new Set(['https://studio.bonyatech.com', 'https://portofile001.netlify.app']);
const mime = { '.css':'text/css; charset=utf-8','.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.gif':'image/gif','.svg':'image/svg+xml','.webp':'image/webp','.avif':'image/avif','.ico':'image/x-icon','.xml':'application/xml; charset=utf-8','.txt':'text/plain; charset=utf-8' };
const imageTypes = new Set(['image/jpeg','image/png','image/gif','image/webp','image/avif','image/svg+xml']);
const projectColumns = ['slug','title_en','title_ar','category_en','category_ar','short_description_en','short_description_ar','long_description_en','long_description_ar','tech_stack','project_url','github_url','additional_url','cover_image_url','cover_image_path','gallery_images','gallery_captions','media_type','media_fit','media_scale','media_position_x','media_position_y','angled_edge','features','main_features','project_type','project_role','project_year','project_duration','project_platform','project_status_label','challenge_ar','challenge_en','solution_ar','solution_en','development_notes_ar','development_notes_en','limitations_ar','limitations_en','next_steps_ar','next_steps_en','status','featured','visible','sort_order'];
const mediaTypes = new Set(['cover','logo','screenshot','poster']);
const mediaFits = new Set(['contain','cover']);
const mediaPositionsX = new Set(['left','center','right']);
const mediaPositionsY = new Set(['top','center','bottom']);
const featureIcons = new Set(['route','globe','layers','code','database','cloud','map-pin','search','article','chart']);

const json = (res, status, body, headers = {}) => { res.writeHead(status,{ 'Content-Type':'application/json; charset=utf-8','X-Content-Type-Options':'nosniff',...headers }); res.end(JSON.stringify(body)); };
const cookies = (req) => Object.fromEntries((req.headers.cookie || '').split(';').map(v=>v.trim().split('=').map(decodeURIComponent)).filter(v=>v.length===2));
const sign = (payload) => createHmac('sha256',secret).update(payload).digest('base64url');
const sessionFor = (email) => { const payload = Buffer.from(JSON.stringify({email,exp:Date.now()+43200000})).toString('base64url'); return `${payload}.${sign(payload)}`; };
const currentUser = (req) => { try { const [payload,signature]=String(cookies(req).studio_session||'').split('.'); if (!payload || !signature || !timingSafeEqual(Buffer.from(signature),Buffer.from(sign(payload)))) return null; const data=JSON.parse(Buffer.from(payload,'base64url')); return data.exp>Date.now() && data.email===adminEmail ? {email:data.email} : null; } catch { return null; } };
const safePath = (value) => typeof value==='string' && /^projects\/[a-zA-Z0-9._-]+$/.test(value) ? value : null;
const mediaUrl = (path, isPublic=false) => path ? `${isPublic?'/media-public/':'/media/'}${encodeURIComponent(path).replace(/%2F/g,'/')}` : null;
const cleanFeature = (item, index) => {
  if (!item || typeof item !== 'object') return null;
  const value = (field) => typeof item[field] === 'string' ? item[field].slice(0, 120) : '';
  const icon = featureIcons.has(item.icon) ? item.icon : 'check';
  const title = value('title_ar') || value('title_en');
  if (!title) return null;
  return { title_ar: value('title_ar'), title_en: value('title_en'), description_ar: value('description_ar'), description_en: value('description_en'), icon, order: Number.isInteger(Number(item.order)) ? Number(item.order) : index };
};
const mapProject = (project, isPublic=false) => ({...project,cover_image_url:project.cover_image_url || mediaUrl(project.cover_image_path,isPublic),gallery_images:(project.gallery_images||[]).map(path=>mediaUrl(path,isPublic)),features:Array.isArray(project.features)?project.features:[],gallery_captions:project.gallery_captions && typeof project.gallery_captions==='object'?project.gallery_captions:{}});
const mapFeatures = (raw) => JSON.stringify((Array.isArray(raw)?raw:[]).map(cleanFeature).filter(Boolean).slice(0,4));
const mapCaptions = (raw) => { const source = raw && typeof raw==='object' ? raw : {}; const captions = {}; for (const [path, caption] of Object.entries(source)) { if (safePath(path) && typeof caption==='string') captions[path] = caption.slice(0, 220); } return JSON.stringify(captions); };
const mapMainFeatures = (raw) => JSON.stringify((Array.isArray(raw)?raw:[]).filter((item) => typeof item==='string').map((item) => item.slice(0,120)).slice(0,12));
const validUrl = (value) => { if (!value) return true; try { return ['http:','https:'].includes(new URL(value).protocol); } catch { return false; } };
const safeSvg = (bytes) => { const source = bytes.toString('utf8'); return source.length > 0 && source.length <= 10 * 1024 * 1024 && /^\s*(?:<\?xml[^>]*>\s*)?<svg\b/i.test(source) && !/<\s*(?:script|foreignObject|iframe|object|embed)\b/i.test(source) && !/\son\w+\s*=/i.test(source) && !/(?:javascript:|data:text\/html)/i.test(source); };

async function body(req, max=10*1024*1024) { const chunks=[]; let length=0; for await (const chunk of req) { length+=chunk.length; if(length>max) throw new Error('Payload too large.'); chunks.push(chunk); } return Buffer.concat(chunks); }
async function authorized(req,res) { const user=currentUser(req); if(!user) { json(res,401,{error:'Authentication required.'}); return null; } if (['POST','PATCH','PUT','DELETE'].includes(req.method) && req.headers.origin && !allowedOrigins.has(req.headers.origin)) { json(res,403,{error:'Invalid request origin.'}); return null; } return user; }
async function serve(res,file) { try { const info=await stat(file); if(!info.isFile()) return false; const extension=extname(file); const cache=['.html','.js','.css'].includes(extension)?'no-cache':'public, max-age=3600'; res.writeHead(200,{'Content-Type':mime[extension]||'application/octet-stream','X-Content-Type-Options':'nosniff','Cache-Control':cache}); createReadStream(file).pipe(res); return true; } catch{return false;} }
function projectPayload(raw) { const data={}; for(const key of projectColumns) if(key in raw) data[key]=raw[key]; data.slug=String(data.slug||'').trim().toLowerCase(); if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(data.slug)) throw new Error('Invalid slug.'); if(!data.title_en||!data.title_ar||!data.category_en||!data.category_ar||!data.short_description_en||!data.short_description_ar) throw new Error('Required project fields are missing.'); if (String(data.cover_image_url||'').startsWith('/media/')) data.cover_image_url=null; if(!validUrl(data.project_url)||!validUrl(data.github_url)||!validUrl(data.cover_image_url)||!validUrl(data.additional_url)) throw new Error('Project URLs must use http or https.'); data.tech_stack=JSON.stringify(Array.isArray(data.tech_stack)?data.tech_stack:[]); data.gallery_images=JSON.stringify((Array.isArray(data.gallery_images)?data.gallery_images:[]).filter(safePath)); data.gallery_captions=mapCaptions(data.gallery_captions); data.cover_image_path=safePath(data.cover_image_path); data.media_type=mediaTypes.has(data.media_type)?data.media_type:'cover'; data.media_fit=data.media_type==='logo'?'contain':(mediaFits.has(data.media_fit)?data.media_fit:(data.media_type==='cover'?'cover':'contain')); data.media_scale=Math.min(1.15,Math.max(.4,Number(data.media_scale)||1)); data.media_position_x=mediaPositionsX.has(data.media_position_x)?data.media_position_x:'center'; data.media_position_y=mediaPositionsY.has(data.media_position_y)?data.media_position_y:'center'; data.angled_edge=Boolean(data.angled_edge); data.features=mapFeatures(data.features); data.main_features=mapMainFeatures(data.main_features); data.project_type=String(data.project_type||'').slice(0,80); data.project_role=String(data.project_role||'').slice(0,80); data.project_year=String(data.project_year||'').slice(0,12); data.project_duration=String(data.project_duration||'').slice(0,80); data.project_platform=String(data.project_platform||'').slice(0,80); data.project_status_label=String(data.project_status_label||'').slice(0,80); data.challenge_ar=String(data.challenge_ar||'').slice(0,2000); data.challenge_en=String(data.challenge_en||'').slice(0,2000); data.solution_ar=String(data.solution_ar||'').slice(0,2000); data.solution_en=String(data.solution_en||'').slice(0,2000); data.development_notes_ar=String(data.development_notes_ar||'').slice(0,2000); data.development_notes_en=String(data.development_notes_en||'').slice(0,2000); data.limitations_ar=String(data.limitations_ar||'').slice(0,2000); data.limitations_en=String(data.limitations_en||'').slice(0,2000); data.next_steps_ar=String(data.next_steps_ar||'').slice(0,2000); data.next_steps_en=String(data.next_steps_en||'').slice(0,2000); data.status=['draft','published','private','development','archived'].includes(data.status)?data.status:'draft'; data.visible=Boolean(data.visible); data.featured=Boolean(data.featured); data.sort_order=Number.isInteger(Number(data.sort_order))?Number(data.sort_order):0; return data; }
async function api(req,res,url) {
  const path=url.pathname;
  if(path==='/api/auth/session') return json(res,200,{user:currentUser(req)});
  if(path==='/api/auth/logout' && req.method==='POST') return json(res,200,{ok:true},{'Set-Cookie':'studio_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0'});
  if(path==='/api/auth/login' && req.method==='POST') { const data=JSON.parse((await body(req,8192)).toString()); const result=await pool.query('select password_hash from studio_users where email=$1',[String(data.email||'').toLowerCase()]); const [salt,hash]=(result.rows[0]?.password_hash||':').split(':'); const candidate=salt?scryptSync(String(data.password||''),salt,64).toString('hex'):''; if(!hash||!timingSafeEqual(Buffer.from(candidate||'0'),Buffer.from(hash))) return json(res,401,{error:'Invalid email or password.'}); return json(res,200,{user:{email:adminEmail}},{'Set-Cookie':`studio_session=${sessionFor(adminEmail)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=43200`}); }
  if(path==='/api/public/projects' && req.method==='GET') { const rows=await pool.query(`select ${projectColumns.join(',')} from projects where status='published' and visible=true order by sort_order asc`); return json(res,200,{projects:rows.rows.map(row=>mapProject(row,true))},{'Access-Control-Allow-Origin':'https://portofile001.netlify.app','Cache-Control':'public, max-age=60'}); }
  if(path==='/api/projects' && req.method==='GET') { if(!await authorized(req,res))return; const rows=await pool.query('select * from projects order by sort_order asc'); return json(res,200,{projects:rows.rows.map(row=>mapProject(row))}); }
  if(path==='/api/projects' && req.method==='POST') { if(!await authorized(req,res))return; try { const data=projectPayload(JSON.parse((await body(req)).toString())); const keys=Object.keys(data); const values=keys.map(k=>data[k]); const row=await pool.query(`insert into projects (${keys.join(',')}) values (${keys.map((_,i)=>`$${i+1}`).join(',')}) returning *`,values); return json(res,201,{project:mapProject(row.rows[0])}); } catch(error){return json(res,400,{error:error.message});} }
  const projectMatch=path.match(/^\/api\/projects\/([a-f0-9-]+)$/i);
  if(projectMatch && req.method==='PATCH') { if(!await authorized(req,res))return; try { const existing=await pool.query('select * from projects where id=$1',[projectMatch[1]]); if(!existing.rows[0]) return json(res,404,{error:'Project not found.'}); const data=projectPayload({...existing.rows[0],...JSON.parse((await body(req)).toString())}); const keys=Object.keys(data); const values=keys.map(k=>data[k]); values.push(projectMatch[1]); const row=await pool.query(`update projects set ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')} where id=$${values.length} returning *`,values); return json(res,200,{project:mapProject(row.rows[0])}); } catch(error){return json(res,400,{error:error.message});} }
  if(projectMatch && req.method==='DELETE') { if(!await authorized(req,res))return; try { const row=await pool.query('delete from projects where id=$1 returning cover_image_path,gallery_images',[projectMatch[1]]); if(!row.rows[0]) return json(res,404,{error:'Project not found.'}); const paths=[row.rows[0].cover_image_path,...(row.rows[0].gallery_images||[])].filter(safePath); await Promise.all(paths.map(path=>unlink(resolve(mediaDir,path)).catch(()=>{}))); return json(res,200,{ok:true}); } catch(error){return json(res,400,{error:error.message});} }
  if(path==='/api/media' && req.method==='PUT') { if(!await authorized(req,res))return; const filePath=safePath(url.searchParams.get('path')); const contentType=req.headers['content-type']||''; if(!filePath||!imageTypes.has(contentType)) return json(res,400,{error:'Invalid image upload.'}); try { const bytes=await body(req); if(contentType==='image/svg+xml'&&!safeSvg(bytes)) return json(res,400,{error:'Unsafe SVG upload.'}); await mkdir(resolve(mediaDir,'projects'),{recursive:true}); const target=resolve(mediaDir,filePath); if(!target.startsWith(mediaDir)||existsSync(target)) return json(res,409,{error:'Image path already exists.'}); await writeFile(target,bytes,{flag:'wx'}); return json(res,201,{path:filePath}); } catch(error){return json(res,400,{error:error.message});} }
  if(path.startsWith('/media/')) { if(!await authorized(req,res))return; const target=resolve(mediaDir,decodeURIComponent(path.slice(7))); if(await serve(res,target)) return; return json(res,404,{error:'Image not found.'}); }
  if(path.startsWith('/media-public/')) { const filePath=safePath(decodeURIComponent(path.slice(14))); if(!filePath)return json(res,404,{error:'Image not found.'}); const result=await pool.query("select 1 from projects where status='published' and visible=true and (cover_image_path=$1 or gallery_images ? $1) limit 1",[filePath]); if(!result.rows[0])return json(res,404,{error:'Image not found.'}); if(await serve(res,resolve(mediaDir,filePath))) return; return json(res,404,{error:'Image not found.'}); }
  return false;
}

const server=createServer(async(req,res)=>{ try { const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`); if(url.pathname.startsWith('/api/')||url.pathname.startsWith('/media')) { const handled=await api(req,res,url); if(handled!==false)return; } const pathname=decodeURIComponent(url.pathname); const requested=pathname==='/'?'index.html':(pathname.endsWith('/')?`${pathname}index.html`:pathname); const candidate=normalize(join(publicDir,requested)); if(candidate.startsWith(publicDir)&&existsSync(candidate)&&await serve(res,candidate))return; if(pathname.startsWith('/studio'))return void await serve(res,join(publicDir,'studio','index.html')); await serve(res,join(publicDir,'index.html')); } catch(error){ json(res,500,{error:'Server error.'}); } });
await mkdir(mediaDir,{recursive:true});
server.listen(port,'127.0.0.1',()=>console.log(`Portfolio Studio listening on ${port}`));
